# Generated by Django 4.2 on 2025-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zips', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('account_type', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
