# Generated by Django 5.0.7 on 2025-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_customer_customer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_images',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
    ]
