# Generated by Django 5.1.7 on 2025-03-23 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_customuser_security_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='flow_direction',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.transfer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customuser'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='flow_direction',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
