# Generated by Django 5.0.6 on 2025-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_transaction_flow_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_images',
            field=models.ImageField(blank=True, default='D:\\Samanyastra\x08ankapplications_final\\default.jpeg', null=True, upload_to='customer_images/'),
        ),
    ]
